language: php
sudo: false

php:
- 5.6
- 5.5
- 5.4

services:
- redis-server

before_script:
- composer self-update
- composer install --no-interaction

script:
- vendor/bin/phpunit

matrix:
  fast_finish: true